import ExtendedMath from "./extended_math.js";

export default class MemoryBankGenerator {
    numberOfLocations;

    generatedData = [];
    
    constructor(numberOfLocations) {
        this.numberOfLocations = numberOfLocations;
    }

    /**
     * 
     * @param {(bankIndex, bankPosition) => number} callback 
     * @returns
     */
    generate(callback){
        const bankArrayData = [];
        for (let bankPosition = 0; bankPosition < this.numberOfLocations; bankPosition++) {
            bankArrayData.push(this.generateOne(callback, bankPosition));
        }
        this.generatedData = bankArrayData;
    }

    generateOne(callback, bankPosition) {
        const bankData = ExtendedMath.sample(256, callback, bankPosition);
        const bankDataStrings = new Array(this.countMemoryBanksRequired(bankData)).fill("");
        for (const bankValue of bankData) {
            for (const digitIndex in bankDataStrings) {
                bankDataStrings[digitIndex] += ExtendedMath.getHexDigit(bankValue, digitIndex);
            }
        }
        return bankDataStrings
    }

    countMemoryBanksRequired(bankData) {
        const biggestValue = Math.max(...bankData);
        return Math.ceil(ExtendedMath.getBaseLog(16, biggestValue + 1));
    }

    getFormattedData(){
        return this.generatedData
            .map(element => element
                .map(element => insertNewlines(element)));

        /**
         * generated by ChatGPT
         * @param {string} str 
         * @param {number} interval 
         * @returns 
         */
        function insertNewlines(str, interval = 16) {
            return str.replace(new RegExp(`(.{${interval}})`, 'g'), '$1\n');//
        }
    }

    /**
     * 
     * @param {HTMLParagraphElement} element 
     */
    write(element) {
        element.innerHTML = this.getFormattedData()[0].reduce(
            (previous, element) => previous.concat(element.replace(/\n/g, '<br>')),
            ''
        );
        console.log(element.innerHTML);
        // element.textContent
    }
}
